### ISSUE TITLE
FAILED

### ISSUE THREAD

**Issue by divined** [weareinteractive/ansible-mongodb#3]
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "file (/var/log/mongodb/mongod.log) is absent, cannot continue", "path": "/var/log/mongodb/mongod.log", "state": "absent"}

**Comment by divined** [comment]
state: file => state: touch

**Comment by franklinkim** [comment]
Hi, could you provide some more information on this... OS, Playbook...

**Comment by divined** [comment]
Ubuntu 16. I think it is enough )
I not use vagrant anymore. Very slow (

**Comment by franklinkim** [comment]
Think I fixed this with 1.4.0 (941377bf17196b99738e38e099ccd5a41c24e500). Also bumped the default version to 3.4
